// <auto-generated />
namespace Variedades.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_company));
        
        string IMigrationMetadata.Id
        {
            get { return "201903180134150_remove_company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
